"""Streamlit viewer for the geometry-import pipeline (issues #172-#175).

Run with::

    streamlit run app/main.py

Purpose
-------
A developer/test viewer, not the product UI. It exists to make the geometry
pipeline *visible* -- upload an object, watch it become a mesh, then a sign
field, then phi -- so problems surface as something you can look at rather than
as a failing assertion.

The product dashboard is #130 / #137; this is its proving ground.

Layering rule
-------------
This app imports ``srm_burnback``; the package never imports Streamlit. All the
real logic lives in the package and is testable without a UI. Anything here
should be presentation only.
"""

from __future__ import annotations

import sys
import tempfile
from pathlib import Path

import streamlit as st
import torch

# Make the package importable when run via `streamlit run` from the repo root.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from srm_burnback.geometry.import_mesh import (  # noqa: E402
    MeshImportError,
    estimate_winding_cost,
    grid_for_mesh,
    load_mesh,
    mesh_stats,
)

SAMPLE_DIR = Path(__file__).resolve().parent.parent / "examples" / "output" / "meshes"

st.set_page_config(page_title="SRM Burnback - Geometry", layout="wide")


# --------------------------------------------------------------------------
# Loading (cached so slider changes don't re-parse the file)
# --------------------------------------------------------------------------

@st.cache_data(show_spinner=False)
def _load_from_bytes(data: bytes, suffix: str):
    """Load a mesh from raw bytes, returning (mesh, stats).

    Cached on the file contents, so moving the resolution slider does not
    re-parse a multi-megabyte STL. trimesh wants a path, so the bytes are
    staged through a temp file.
    """
    with tempfile.NamedTemporaryFile(suffix=suffix, delete=False) as fh:
        fh.write(data)
        tmp_path = fh.name
    try:
        mesh = load_mesh(tmp_path)
        return mesh, mesh_stats(mesh)
    finally:
        Path(tmp_path).unlink(missing_ok=True)


def _fmt(x: float, digits: int = 4) -> str:
    return f"{x:.{digits}g}"


# --------------------------------------------------------------------------
# Sidebar: input selection and grid controls
# --------------------------------------------------------------------------

st.sidebar.title("Geometry")

source = st.sidebar.radio(
    "Source", ["Sample mesh", "Upload"], horizontal=True,
    help="Samples are generated by examples/make_test_meshes.py",
)

mesh = None
stats = None
source_name = None

if source == "Upload":
    uploaded = st.sidebar.file_uploader(
        "Mesh file", type=["stl", "obj", "ply", "off", "glb", "gltf"]
    )
    if uploaded is not None:
        try:
            mesh, stats = _load_from_bytes(
                uploaded.getvalue(), Path(uploaded.name).suffix
            )
            source_name = uploaded.name
        except MeshImportError as exc:
            st.sidebar.error(str(exc))
else:
    samples = sorted(SAMPLE_DIR.glob("*.stl")) if SAMPLE_DIR.exists() else []
    if not samples:
        st.sidebar.warning(
            "No sample meshes found.\n\n"
            "Generate them with:\n\n"
            "`python examples/make_test_meshes.py`"
        )
    else:
        chosen = st.sidebar.selectbox(
            "Sample", samples, format_func=lambda p: p.name
        )
        try:
            mesh, stats = _load_from_bytes(chosen.read_bytes(), chosen.suffix)
            source_name = chosen.name
        except MeshImportError as exc:
            st.sidebar.error(str(exc))

st.sidebar.divider()
st.sidebar.subheader("Grid")

resolution = st.sidebar.select_slider(
    "Resolution (points per axis)",
    options=[32, 48, 64, 96, 128, 192, 256],
    value=64,
    help="The grid is volumetric: resolution^3 cells cover the whole object.",
)

margin = st.sidebar.slider(
    "Domain margin", 0.0, 0.5, 0.05, 0.01,
    help="Padding beyond the mesh so the burn front never reaches the "
         "grid edge, where the Neumann ghost cells live.",
)

cuda_available = torch.cuda.is_available()
device = st.sidebar.radio(
    "Device", ["cuda", "cpu"] if cuda_available else ["cpu"],
    horizontal=True,
    help="The winding number is embarrassingly parallel and enormously "
         "faster on GPU.",
)
if cuda_available:
    st.sidebar.caption(f"GPU: {torch.cuda.get_device_name(0)}")
else:
    st.sidebar.caption("No CUDA device detected - see issue #29")


# --------------------------------------------------------------------------
# Main panel
# --------------------------------------------------------------------------

st.title("Grain geometry import")
st.caption(
    "object -> mesh -> winding-number sign field -> numerical distance -> "
    "phi.  Developer viewer for issue #172."
)

if mesh is None:
    st.info(
        "Choose a sample mesh or upload one to begin.\n\n"
        "If no samples are listed, generate them first:\n\n"
        "```\npython examples/make_test_meshes.py\n```"
    )
    st.stop()

n_cells = resolution ** 3
coords, h = grid_for_mesh(mesh, resolution, margin=margin, device=device)

tab_stats, tab_view, tab_phi = st.tabs(
    ["Mesh", "3D preview", "Signed distance field"]
)

# --- Mesh statistics ------------------------------------------------------

with tab_stats:
    st.subheader(source_name or "mesh")

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Triangles", f"{stats['n_triangles']:,}")
    c2.metric("Vertices", f"{stats['n_vertices']:,}")
    c3.metric(
        "Watertight",
        "yes" if stats["watertight"] else "no",
        help="A non-watertight mesh is exactly the case the generalized "
             "winding number handles gracefully and ray casting does not.",
    )
    c4.metric(
        "Degenerate faces",
        stats["n_degenerate"],
        help="Zero-area triangles subtend an undefined solid angle.",
    )

    if not stats["watertight"]:
        st.warning(
            "This mesh is **not watertight** - it has holes or boundary "
            "edges. That is supported: the generalized winding number "
            "degrades gracefully rather than mis-signing (#158). Ray "
            "casting would produce wrong signs here."
        )
    if stats["n_degenerate"]:
        st.warning(
            f"{stats['n_degenerate']} degenerate (zero-area) faces. These "
            "contribute no solid angle and are skipped, but a large count "
            "suggests a damaged mesh."
        )

    st.divider()
    st.markdown("**Extents** - check these against the units you expect")

    ex = stats["extents"]
    e1, e2, e3 = st.columns(3)
    e1.metric("X", _fmt(ex[0]))
    e2.metric("Y", _fmt(ex[1]))
    e3.metric("Z", _fmt(ex[2]))

    if stats["max_extent"] > 10.0:
        st.warning(
            "Largest extent exceeds 10. If this grain is in **millimetres**, "
            "the simulation works in metres and the geometry will be ~1000x "
            "too large. STL files carry no unit declaration, so this cannot "
            "be detected automatically (native CAD formats do - see #170)."
        )

    st.divider()
    m1, m2 = st.columns(2)
    m1.metric("Surface area", _fmt(stats["surface_area"]))
    m2.metric(
        "Volume",
        _fmt(stats["volume"]) if stats["volume"] is not None else "n/a",
        help="Only well defined for a closed surface.",
    )

    st.divider()
    st.markdown("**Grid that will be built**")
    g1, g2, g3 = st.columns(3)
    g1.metric("Cells", f"{n_cells:,}", help=f"{resolution}^3")
    g2.metric("Spacing h", _fmt(h))
    g3.metric(
        "Cells across bore",
        f"{ex[0] / h:.0f}" if h > 0 else "-",
        help="How many cells span the object. Too few and the geometry "
             "is under-resolved.",
    )

    cost = estimate_winding_cost(n_cells, stats["n_triangles"], device)
    if cost > 60:
        st.error(
            f"Estimated winding-number time: **{cost/60:.1f} min** on "
            f"{device}. Lower the resolution or switch device."
        )
    elif cost > 5:
        st.warning(f"Estimated winding-number time: **{cost:.0f} s** on {device}.")
    else:
        st.success(f"Estimated winding-number time: **{cost:.1f} s** on {device}.")

# --- 3D preview -----------------------------------------------------------

with tab_view:
    st.subheader("Mesh surface")
    style = st.radio(
        "Style", ["surface", "wireframe"], horizontal=True,
        help="Wireframe shows tessellation density - compare it against "
             "the grid spacing.",
    )
    try:
        import pyvista as pv
        from stpyvista import stpyvista

        pv_mesh = pv.wrap(mesh)
        plotter = pv.Plotter(window_size=[600, 500])
        plotter.add_mesh(
            pv_mesh,
            style="wireframe" if style == "wireframe" else "surface",
            color="#c96a3a",
            show_edges=(style == "surface"),
            edge_color="#6b3a20",
            line_width=1,
        )
        plotter.add_axes()
        plotter.view_isometric()
        plotter.background_color = "#1e1e1e"
        stpyvista(plotter, key=f"mesh-{source_name}-{style}")
    except Exception as exc:  # rendering must never take down the app
        st.error(f"3D preview unavailable: {exc}")
        st.caption(
            "The rest of the pipeline is unaffected - this panel is "
            "display only."
        )

# --- phi ------------------------------------------------------------------

with tab_phi:
    st.subheader("Signed distance field")
    st.info(
        "**Not implemented yet.** This panel needs the generalized "
        "winding number (#158), which is the next thing to build.\n\n"
        "Once it lands, this will show a slice through the volumetric "
        "phi field with the zero contour drawn, plus the |grad phi| "
        "diagnostic that tells us whether the import produced a valid "
        "signed distance field."
    )

    st.markdown(
        """
**What will run here**

```
mesh triangles
     |
     v
generalized winding number   -> sign  (+1 void / -1 propellant)   #158
     |
     v
brute-force nearest-interface distance                            #3 (done)
     |
     v
phi  ->  slice view  +  |grad phi| histogram
```

The headline check is `|grad phi| ~= 1`. That is the defining property
of a signed distance field, and every downstream numerical method
assumes it. Phase 1 verified it on analytically generated fields; it
has never been checked on geometry derived from a real mesh.
"""
    )

    st.caption(
        f"Grid ready: {n_cells:,} cells, h = {_fmt(h)}, device = {device}"
    )
